### PR TITLE
Add support for an environment.ini file

### PR DESCRIPTION
**Pull request by richardherbert**
This offers an alternative to system or environment properties where access is unavailable, for example where shared hosting is used.

### CODE REVIEW

**Comment by elpete** [comment]
Correct me if I'm wrong, but this pull request doesn't add support for `.ini` files to the library, just the tests.

That being said, I think I would say that the `.ini` file parsing would make the most sense in the `Application.cfc`  You could add the properties to the Java System using [`system.setProperty()`](https://docs.oracle.com/javase/7/docs/api/java/lang/System.html#setProperty(java.lang.String,%20java.lang.String)).  This would let you keep a consistent way of accessing secrets (via env or system properties) whether using shared hosting, docker containers, VPS, or whatever.

**Comment by infoweb** [comment]
Yes, but you could use this with the production code. Or am I missing something?

I was just following your changes for the system properties. I have a situation where I can't set system/environment properties.

I could have put my `ini` file support to the `Application.cfc` but I thought it was better to keep it close to your changes.

**Comment by richardherbert** [comment]
Yes, but you could use this with the production code. Or am I missing something?

I was just following your changes for the system properties. I have a situation where I can't set system/environment properties.

I could have put my ini file support to the Application.cfc but I thought it was better to keep it close to your changes.

**Comment by elpete** [comment]
My points were two fold:
1. The changes in this pull request only change test code.  I would assume that tests would be ran locally via CommandBox.  In those cases, [`commandbox-dotenv`](https://www.forgebox.io/view/commandbox-dotenv) would add these values to system properties for you.
2. As far as using this in production, I completely understand not being able to set ENV vars or Java System Properties.  You should still be able to use the library as is by setting the appropriate module settings:

```
moduleSettings = {
    cbgithub = {
        "username" = "myUserName",
        "password" = "myPassword"
    }
};

// or like this if you want to use your personal access token...

moduleSettings = {
    cbgithub = {
        "token" = "myPersonalToken"
    }
};
```
You could read in your `.ini` file in your `config/ColdBox.cfc` and use the values there.  My suggestion before was to maybe even add the values in the `.ini` file to the system properties at runtime using [`java.lang.System.setProperty`](https://docs.oracle.com/javase/7/docs/api/java/lang/System.html#setProperty(java.lang.String,%20java.lang.String)) so you could still access it the same (using a `getSystemSetting` helper of some sort), but this is not required.

Hopefully this helps explain my thoughts a bit better?

**Comment by richardherbert** [comment]
I see my suggestions solve an issue I have rather than useful for the project as a whole so I'll withdraw this pull request.

**Pull request closed without merging**
